repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.5
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: trailing-whitespace
  - id: check-docstring-first
  - id: end-of-file-fixer
  - id: mixed-line-ending

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.37.0
  hooks:
  - id: check-github-workflows
